### ISSUE TITLE
KeyError: 'GlyphOrder' when I merge all weights of NotoSansCanadianAboriginal + NotoSans

### ISSUE THREAD

**Issue by marekjez86** [notofonts/noto-build#13]
noto-build % python3 ./notobuilderCLI.py --name "NotoSansCanadiana" --output ttf --scripts CanadianAboriginal Latin --contrast Sans --weight Thin ExtraLight Light Regular ExtraBold Bold SemiBold Medium Black

['NotoSansCanadianAboriginal', 'NotoSans']
INFO: Download begin

> The followings fonts can be merged:
  ✓ NotoSansCanadianAboriginal-Thin.ttf
  ✓ NotoSans-Thin.ttf

    WARN: U+0000 U+0020 U+02C7 U+25CC U+000D U+02D8 U+02D9 U+02DA U+02DB are removed from NotoSans-Thin.ttf
    INFO: NotoSans subseted
    INFO: starts merging
    INFO: ends merging

> The followings fonts can be merged:
No font matches the requirements. The script NotoSansCanadianAboriginal is removed from the list
No font matches the requirements. The script NotoSans is removed from the list
    INFO: starts merging
Traceback (most recent call last):
  File "./notobuilderCLI.py", line 877, in <module>
    sys.exit(main())
  File "./notobuilderCLI.py", line 872, in main
    subs
  File "./notobuilderCLI.py", line 259, in __init__
    self.buildRepoName()
  File "./notobuilderCLI.py", line 358, in buildRepoName
    self.buildWghtWdthstyleName()
  File "./notobuilderCLI.py", line 384, in buildWghtWdthstyleName
    self.buildFonts2mergeList()
  File "./notobuilderCLI.py", line 454, in buildFonts2mergeList
    self.prepFontsForMerging()
  File "./notobuilderCLI.py", line 550, in prepFontsForMerging
    self.merging()
  File "./notobuilderCLI.py", line 562, in merging
    self.font = merger.merge(self.actualFonts2merge)
  File "/Users/marek/Library/Python/3.7/lib/python/site-packages/fontTools/merge.py", line 1020, in merge
    allTags.remove('GlyphOrder')
KeyError: 'GlyphOrder'

NOTE: that I can do it one by one

**Comment by jbmorizot** [comment]
I cleaned the downloaded font folder too soon in the process. I push the fix.
