### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './NotoFonts/NotoSansBrahmi/sha.md'

### ISSUE THREAD

**Issue by marekjez86** [notofonts/noto-build#21]
====== Sans Brahmi
Traceback (most recent call last):
  File "./notobuilderCLI.py", line 1244, in <module>
    sys.exit(main())
  File "./notobuilderCLI.py", line 1239, in main
    version
  File "./notobuilderCLI.py", line 334, in __init__
    dl.dwnldFonts()
  File "./notobuilderCLI.py", line 121, in dwnldFonts
    if self.oldSha(i) == self.getSha(i):
  File "./notobuilderCLI.py", line 53, in oldSha
    with open(oldShaPath, "r") as text:
FileNotFoundError: [Errno 2] No such file or directory: './NotoFonts/NotoSansBrahmi/sha.md'

**Comment by nizarsq** [comment]
I was able to merge NotoSansBrahmi, I didn't have the any complaint about  sha.md file ( I got HTTP limit exceeded Error when it reaches Serif CaucasianAlbanian, which I believe it is unrelated issue). (First output below). 

Regarding the issue reported with missing sha.md file, I checked NotoFonts/NotoSansBrahm directory and it was there. @marekjez86 did you check if sha.md exist in NotoFonts/NotoSansBrahm directory? 

###########
for i in Brahmi Buginese Buhid CanadianAboriginal Carian CaucasianAlbanian Chakma Cham ; do echo "====== Sans $i"; python3 ./notobuilderCLI.py --name "NotoSans-$i" --output ttf --scripts Latin Greek Cyrillic $i --contrast Sans --weight Regular Medium SemiBold Bold --width Normal --preset ExtendedCyrillic ExtendedGreek UnicodeLatin ; sleep 36; echo "====== Serif $i"; python3 ./notobuilderCLI.py --name "NotoSerif-$i" --output ttf --scripts Latin Greek Cyrillic $i --contrast Serif --weight Regular Medium SemiBold Bold --width Normal --preset ExtendedCyrillic ExtendedGreek UnicodeLatin ; sleep 36; done
====== Sans Brahmi
INFO: NotoSansBrahmi download begin
> Gather fonts to build NotoSans-Brahmi Regular
> The followings fonts can be merged:
  ✓ NotoSans-Regular.ttf
  ✓ NotoSansBrahmi-Regular.ttf

    WARN: U+0000 U+0020 U+00A0 U+200B U+200C U+200D U+000D U+25CC are removed from NotoSansBrahmi-Regular.ttf
    INFO: NotoSansBrahmi subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSans-Brahmi Medium
> The followings fonts can be merged:
  ✓ NotoSans-Medium.ttf
  ✓ NotoSansBrahmi-Regular.ttf [FALLBACK]
    INFO: NotoSansBrahmi subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSans-Brahmi SemiBold
> The followings fonts can be merged:
  ✓ NotoSans-SemiBold.ttf
  ✓ NotoSansBrahmi-Regular.ttf [FALLBACK]
    INFO: NotoSansBrahmi subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSans-Brahmi Bold
> The followings fonts can be merged:
  ✓ NotoSans-Bold.ttf
  ✓ NotoSansBrahmi-Regular.ttf [FALLBACK]
    INFO: NotoSansBrahmi subseted
    INFO: starts merging
    INFO: ends merging

====== Serif Brahmi
> Gather fonts to build NotoSerif-Brahmi Regular
> The followings fonts can be merged:
  ✓ NotoSerif-Regular.ttf
  ✓ NotoSansBrahmi-Regular.ttf

    WARN: U+0000 U+0020 U+00A0 U+200B U+200C U+200D U+000D U+25CC are removed from NotoSansBrahmi-Regular.ttf
    INFO: NotoSansBrahmi subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSerif-Brahmi Medium
> The followings fonts can be merged:
  ✓ NotoSerif-Medium.ttf
  ✓ NotoSansBrahmi-Regular.ttf [FALLBACK]
    INFO: NotoSansBrahmi subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSerif-Brahmi SemiBold
> The followings fonts can be merged:
  ✓ NotoSerif-SemiBold.ttf
  ✓ NotoSansBrahmi-Regular.ttf [FALLBACK]
    INFO: NotoSansBrahmi subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSerif-Brahmi Bold
> The followings fonts can be merged:
  ✓ NotoSerif-Bold.ttf
  ✓ NotoSansBrahmi-Regular.ttf [FALLBACK]
    INFO: NotoSansBrahmi subseted
    INFO: starts merging
    INFO: ends merging

====== Sans Buginese
INFO: NotoSansBuginese download begin
> Gather fonts to build NotoSans-Buginese Regular
> The followings fonts can be merged:
  ✓ NotoSans-Regular.ttf
  ✓ NotoSansBuginese-Regular.ttf

    WARN: U+0000 U+0020 U+00A0 U+200B U+200C U+000D U+200D U+25CC are removed from NotoSansBuginese-Regular.ttf
    INFO: NotoSansBuginese subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSans-Buginese Medium
> The followings fonts can be merged:
  ✓ NotoSans-Medium.ttf
  ✓ NotoSansBuginese-Regular.ttf [FALLBACK]
    INFO: NotoSansBuginese subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSans-Buginese SemiBold
> The followings fonts can be merged:
  ✓ NotoSans-SemiBold.ttf
  ✓ NotoSansBuginese-Regular.ttf [FALLBACK]
    INFO: NotoSansBuginese subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSans-Buginese Bold
> The followings fonts can be merged:
  ✓ NotoSans-Bold.ttf
  ✓ NotoSansBuginese-Regular.ttf [FALLBACK]
    INFO: NotoSansBuginese subseted
    INFO: starts merging
    INFO: ends merging

====== Serif Buginese
> Gather fonts to build NotoSerif-Buginese Regular
> The followings fonts can be merged:
  ✓ NotoSerif-Regular.ttf
  ✓ NotoSansBuginese-Regular.ttf

    WARN: U+0000 U+0020 U+00A0 U+200B U+200C U+000D U+200D U+25CC are removed from NotoSansBuginese-Regular.ttf
    INFO: NotoSansBuginese subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSerif-Buginese Medium
> The followings fonts can be merged:
  ✓ NotoSerif-Medium.ttf
  ✓ NotoSansBuginese-Regular.ttf [FALLBACK]
    INFO: NotoSansBuginese subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSerif-Buginese SemiBold
> The followings fonts can be merged:
  ✓ NotoSerif-SemiBold.ttf
  ✓ NotoSansBuginese-Regular.ttf [FALLBACK]
    INFO: NotoSansBuginese subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSerif-Buginese Bold
> The followings fonts can be merged:
  ✓ NotoSerif-Bold.ttf
  ✓ NotoSansBuginese-Regular.ttf [FALLBACK]
    INFO: NotoSansBuginese subseted
    INFO: starts merging
    INFO: ends merging

====== Sans Buhid
INFO: NotoSansBuhid download begin
> Gather fonts to build NotoSans-Buhid Regular
> The followings fonts can be merged:
  ✓ NotoSans-Regular.ttf
  ✓ NotoSansBuhid-Regular.ttf

    WARN: U+0000 U+0020 U+00A0 U+200B U+200C U+200D U+000D U+25CC are removed from NotoSansBuhid-Regular.ttf
    INFO: NotoSansBuhid subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSans-Buhid Medium
> The followings fonts can be merged:
  ✓ NotoSans-Medium.ttf
  ✓ NotoSansBuhid-Regular.ttf [FALLBACK]
    INFO: NotoSansBuhid subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSans-Buhid SemiBold
> The followings fonts can be merged:
  ✓ NotoSans-SemiBold.ttf
  ✓ NotoSansBuhid-Regular.ttf [FALLBACK]
    INFO: NotoSansBuhid subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSans-Buhid Bold
> The followings fonts can be merged:
  ✓ NotoSans-Bold.ttf
  ✓ NotoSansBuhid-Regular.ttf [FALLBACK]
    INFO: NotoSansBuhid subseted
    INFO: starts merging
    INFO: ends merging

====== Serif Buhid
> Gather fonts to build NotoSerif-Buhid Regular
> The followings fonts can be merged:
  ✓ NotoSerif-Regular.ttf
  ✓ NotoSansBuhid-Regular.ttf

    WARN: U+0000 U+0020 U+00A0 U+200B U+200C U+200D U+000D U+25CC are removed from NotoSansBuhid-Regular.ttf
    INFO: NotoSansBuhid subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSerif-Buhid Medium
> The followings fonts can be merged:
  ✓ NotoSerif-Medium.ttf
  ✓ NotoSansBuhid-Regular.ttf [FALLBACK]
    INFO: NotoSansBuhid subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSerif-Buhid SemiBold
> The followings fonts can be merged:
  ✓ NotoSerif-SemiBold.ttf
  ✓ NotoSansBuhid-Regular.ttf [FALLBACK]
    INFO: NotoSansBuhid subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSerif-Buhid Bold
> The followings fonts can be merged:
  ✓ NotoSerif-Bold.ttf
  ✓ NotoSansBuhid-Regular.ttf [FALLBACK]
    INFO: NotoSansBuhid subseted
    INFO: starts merging
    INFO: ends merging

====== Sans CanadianAboriginal
INFO: NotoSansCanadianAboriginal download begin
> Gather fonts to build NotoSans-CanadianAboriginal Regular
> The followings fonts can be merged:
  ✓ NotoSans-Regular.ttf
  ✓ NotoSansCanadianAboriginal-Regular.ttf

    WARN: U+0000 U+0020 U+00A0 U+02C7 U+0307 U+25CC U+000D U+0131 U+02D8 U+02D9 U+02DA U+02DB are removed from NotoSansCanadianAboriginal-Regular.ttf
    INFO: NotoSansCanadianAboriginal subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSans-CanadianAboriginal Medium
> The followings fonts can be merged:
  ✓ NotoSans-Medium.ttf
  ✓ NotoSansCanadianAboriginal-Medium.ttf
    INFO: NotoSansCanadianAboriginal subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSans-CanadianAboriginal SemiBold
> The followings fonts can be merged:
  ✓ NotoSans-SemiBold.ttf
  ✓ NotoSansCanadianAboriginal-SemiBold.ttf
    INFO: NotoSansCanadianAboriginal subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSans-CanadianAboriginal Bold
> The followings fonts can be merged:
  ✓ NotoSans-Bold.ttf
  ✓ NotoSansCanadianAboriginal-Bold.ttf
    INFO: NotoSansCanadianAboriginal subseted
    INFO: starts merging
    INFO: ends merging

====== Serif CanadianAboriginal
> Gather fonts to build NotoSerif-CanadianAboriginal Regular
> The followings fonts can be merged:
  ✓ NotoSerif-Regular.ttf
  ✓ NotoSansCanadianAboriginal-Regular.ttf

    WARN: U+0000 U+0020 U+00A0 U+02C7 U+0307 U+25CC U+000D U+0131 U+02D8 U+02D9 U+02DA U+02DB are removed from NotoSansCanadianAboriginal-Regular.ttf
    INFO: NotoSansCanadianAboriginal subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSerif-CanadianAboriginal Medium
> The followings fonts can be merged:
  ✓ NotoSerif-Medium.ttf
  ✓ NotoSansCanadianAboriginal-Medium.ttf
    INFO: NotoSansCanadianAboriginal subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSerif-CanadianAboriginal SemiBold
> The followings fonts can be merged:
  ✓ NotoSerif-SemiBold.ttf
  ✓ NotoSansCanadianAboriginal-SemiBold.ttf
    INFO: NotoSansCanadianAboriginal subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSerif-CanadianAboriginal Bold
> The followings fonts can be merged:
  ✓ NotoSerif-Bold.ttf
  ✓ NotoSansCanadianAboriginal-Bold.ttf
    INFO: NotoSansCanadianAboriginal subseted
    INFO: starts merging
    INFO: ends merging

====== Sans Carian
INFO: NotoSansCarian download begin
> Gather fonts to build NotoSans-Carian Regular
> The followings fonts can be merged:
  ✓ NotoSans-Regular.ttf
  ✓ NotoSansCarian-Regular.ttf

    WARN: U+0000 U+0020 U+000D U+00A0 are removed from NotoSansCarian-Regular.ttf
    INFO: NotoSansCarian subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSans-Carian Medium
> The followings fonts can be merged:
  ✓ NotoSans-Medium.ttf
  ✓ NotoSansCarian-Regular.ttf [FALLBACK]
    INFO: NotoSansCarian subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSans-Carian SemiBold
> The followings fonts can be merged:
  ✓ NotoSans-SemiBold.ttf
  ✓ NotoSansCarian-Regular.ttf [FALLBACK]
    INFO: NotoSansCarian subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSans-Carian Bold
> The followings fonts can be merged:
  ✓ NotoSans-Bold.ttf
  ✓ NotoSansCarian-Regular.ttf [FALLBACK]
    INFO: NotoSansCarian subseted
    INFO: starts merging
    INFO: ends merging

====== Serif Carian
> Gather fonts to build NotoSerif-Carian Regular
> The followings fonts can be merged:
  ✓ NotoSerif-Regular.ttf
  ✓ NotoSansCarian-Regular.ttf

    WARN: U+0000 U+0020 U+000D U+00A0 are removed from NotoSansCarian-Regular.ttf
    INFO: NotoSansCarian subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSerif-Carian Medium
> The followings fonts can be merged:
  ✓ NotoSerif-Medium.ttf
  ✓ NotoSansCarian-Regular.ttf [FALLBACK]
    INFO: NotoSansCarian subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSerif-Carian SemiBold
> The followings fonts can be merged:
  ✓ NotoSerif-SemiBold.ttf
  ✓ NotoSansCarian-Regular.ttf [FALLBACK]
    INFO: NotoSansCarian subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSerif-Carian Bold
> The followings fonts can be merged:
  ✓ NotoSerif-Bold.ttf
  ✓ NotoSansCarian-Regular.ttf [FALLBACK]
    INFO: NotoSansCarian subseted
    INFO: starts merging
    INFO: ends merging

====== Sans CaucasianAlbanian
INFO: NotoSansCaucasianAlbanian download begin
> Gather fonts to build NotoSans-CaucasianAlbanian Regular
> The followings fonts can be merged:
  ✓ NotoSans-Regular.ttf
  ✓ NotoSansCaucasianAlbanian-Regular.ttf

    WARN: U+0000 U+0304 U+000D U+0020 U+00A0 U+FE20 U+FE21 U+FE22 U+FE23 U+FE24 U+FE25 U+FE26 U+FE27 U+FE28 U+FE29 U+FE2A U+FE2B U+FE2C U+FE2D U+FE2E U+0331 U+FE2F U+25CC are removed from NotoSansCaucasianAlbanian-Regular.ttf
    INFO: NotoSansCaucasianAlbanian subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSans-CaucasianAlbanian Medium
> The followings fonts can be merged:
  ✓ NotoSans-Medium.ttf
  ✓ NotoSansCaucasianAlbanian-Regular.ttf [FALLBACK]
    INFO: NotoSansCaucasianAlbanian subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSans-CaucasianAlbanian SemiBold
> The followings fonts can be merged:
  ✓ NotoSans-SemiBold.ttf
  ✓ NotoSansCaucasianAlbanian-Regular.ttf [FALLBACK]
    INFO: NotoSansCaucasianAlbanian subseted
    INFO: starts merging
    INFO: ends merging

> Gather fonts to build NotoSans-CaucasianAlbanian Bold
> The followings fonts can be merged:
  ✓ NotoSans-Bold.ttf
  ✓ NotoSansCaucasianAlbanian-Regular.ttf [FALLBACK]
    INFO: NotoSansCaucasianAlbanian subseted
    INFO: starts merging
    INFO: ends merging

====== Serif CaucasianAlbanian
Traceback (most recent call last):
  File "./notobuilderCLI.py", line 1244, in <module>
    sys.exit(main())
  File "./notobuilderCLI.py", line 1239, in main
    version
  File "./notobuilderCLI.py", line 334, in __init__
    dl.dwnldFonts()
  File "./notobuilderCLI.py", line 121, in dwnldFonts
    if self.oldSha(i) == self.getSha(i):
  File "./notobuilderCLI.py", line 71, in getSha
    response = urllib.request.urlretrieve(api_url)
  File "/Users/nq/.pyenv/versions/3.7.3/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Users/nq/.pyenv/versions/3.7.3/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/nq/.pyenv/versions/3.7.3/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Users/nq/.pyenv/versions/3.7.3/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/nq/.pyenv/versions/3.7.3/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Users/nq/.pyenv/versions/3.7.3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Users/nq/.pyenv/versions/3.7.3/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: rate limit exceeded
====== Sans Chakma
NotoSerif does not exist.Removed from writing system list
NotoSerifChakma does not exist.Removed from writing system list
> Gather fonts to build NotoSans-Chakma Regular
> The followings fonts can be merged:
    INFO: starts merging
Traceback (most recent call last):
  File "./notobuilderCLI.py", line 1244, in <module>
    sys.exit(main())
  File "./notobuilderCLI.py", line 1239, in main
    version
  File "./notobuilderCLI.py", line 337, in __init__
    self.buildWghtWdthstyleName()
  File "./notobuilderCLI.py", line 503, in buildWghtWdthstyleName
    self.buildFonts2mergeList()
  File "./notobuilderCLI.py", line 647, in buildFonts2mergeList
    self.prepFontsForMerging()
  File "./notobuilderCLI.py", line 755, in prepFontsForMerging
    self.merging()
  File "./notobuilderCLI.py", line 767, in merging
    self.font = merger.merge(self.actualFonts2merge)
  File "/Users/nq/.pyenv/versions/3.7.3/lib/python3.7/site-packages/fontTools/merge.py", line 1020, in merge
    allTags.remove('GlyphOrder')
KeyError: 'GlyphOrder'
====== Serif Chakma
NotoSerif does not exist.Removed from writing system list
NotoSerifChakma does not exist.Removed from writing system list
> Gather fonts to build NotoSerif-Chakma Regular
> The followings fonts can be merged:
    INFO: starts merging
Traceback (most recent call last):
  File "./notobuilderCLI.py", line 1244, in <module>
    sys.exit(main())
  File "./notobuilderCLI.py", line 1239, in main
    version
  File "./notobuilderCLI.py", line 337, in __init__
    self.buildWghtWdthstyleName()
  File "./notobuilderCLI.py", line 503, in buildWghtWdthstyleName
    self.buildFonts2mergeList()
  File "./notobuilderCLI.py", line 647, in buildFonts2mergeList
    self.prepFontsForMerging()
  File "./notobuilderCLI.py", line 755, in prepFontsForMerging
    self.merging()
  File "./notobuilderCLI.py", line 767, in merging
    self.font = merger.merge(self.actualFonts2merge)
  File "/Users/nq/.pyenv/versions/3.7.3/lib/python3.7/site-packages/fontTools/merge.py", line 1020, in merge
    allTags.remove('GlyphOrder')
KeyError: 'GlyphOrder'
====== Sans Cham
NotoSerif does not exist.Removed from writing system list
NotoSerifCham does not exist.Removed from writing system list
> Gather fonts to build NotoSans-Cham Regular
> The followings fonts can be merged:
    INFO: starts merging
Traceback (most recent call last):
  File "./notobuilderCLI.py", line 1244, in <module>
    sys.exit(main())
  File "./notobuilderCLI.py", line 1239, in main
    version
  File "./notobuilderCLI.py", line 337, in __init__
    self.buildWghtWdthstyleName()
  File "./notobuilderCLI.py", line 503, in buildWghtWdthstyleName
    self.buildFonts2mergeList()
  File "./notobuilderCLI.py", line 647, in buildFonts2mergeList
    self.prepFontsForMerging()
  File "./notobuilderCLI.py", line 755, in prepFontsForMerging
    self.merging()
  File "./notobuilderCLI.py", line 767, in merging
    self.font = merger.merge(self.actualFonts2merge)
  File "/Users/nq/.pyenv/versions/3.7.3/lib/python3.7/site-packages/fontTools/merge.py", line 1020, in merge
    allTags.remove('GlyphOrder')
KeyError: 'GlyphOrder'
====== Serif Cham
NotoSerif does not exist.Removed from writing system list
NotoSerifCham does not exist.Removed from writing system list
> Gather fonts to build NotoSerif-Cham Regular
> The followings fonts can be merged:
    INFO: starts merging
Traceback (most recent call last):
  File "./notobuilderCLI.py", line 1244, in <module>
    sys.exit(main())
  File "./notobuilderCLI.py", line 1239, in main
    version
  File "./notobuilderCLI.py", line 337, in __init__
    self.buildWghtWdthstyleName()
  File "./notobuilderCLI.py", line 503, in buildWghtWdthstyleName
    self.buildFonts2mergeList()
  File "./notobuilderCLI.py", line 647, in buildFonts2mergeList
    self.prepFontsForMerging()
  File "./notobuilderCLI.py", line 755, in prepFontsForMerging
    self.merging()
  File "./notobuilderCLI.py", line 767, in merging
    self.font = merger.merge(self.actualFonts2merge)
  File "/Users/nq/.pyenv/versions/3.7.3/lib/python3.7/site-packages/fontTools/merge.py", line 1020, in merge
    allTags.remove('GlyphOrder')
KeyError: 'GlyphOrder'
nq@NQs-MacBook-Pro noto-build-master %

**Comment by nizarsq** [comment]
It seems this issue is due to HTTP limit. if sha.md not exist in NotoFonts/NotoSansBrahm directory then delete NotoSansBrahm folder and wait till the limit reset and try again.
